### ISSUE TITLE
Missing CPL file for PCB ordering

### ISSUE THREAD

**Issue by maksm** [mdenisov/feeder#1]
Hey great project, really want to try it out, but this is my first time doing custom PCBs. I wanted to order your design on JLCPCB but in the process the BOM and CPL files are required and here in the repo only the BOM is present - could you also provide the CPL file? I have no idea what it does.

Thanks in advance and cheers for the project.

**Comment by mdenisov** [comment]
@maksm Hi! To order a PCB for JLCPCB, use the included [Gerber](https://github.com/mdenisov/feeder/blob/main/PCB/Feeder_v1_0_Gerber.zip) file for upload in [order page](https://cart.jlcpcb.com/quote). I don`t have a CPL file, sorry. If you tell me how to do it, I'll do it no problem.

**Comment by maksm** [comment]
@mdenisov Hey, yeah I forgot to mention that I wanted the PCB assembly also done, without it only the provided file is ok. But if I wanted to also do the PCB assembly I get to an interface where I have to provide the BOM and CPL files for the project, and am not really sure what those are.

Here is some more info when googling: https://jlcpcb.com/help/article/81-How-to-generate-the-BOM-and-Centroid-file-from-KiCAD

If I can provide any more input or help just let me know!

**Comment by mdenisov** [comment]
@maksm oh, maybe you mean the element positioning file. I was able to export something like [this](https://github.com/mdenisov/feeder/blob/main/PCB/Feeder_v1_0_POS.csv). This is similar to your examples in KiCAD.

If you need anything else, just tell me!

**Comment by maksm** [comment]
![image](https://github.com/mdenisov/feeder/assets/2431416/e20bec79-5183-403a-9877-fbf3e0d62459)

Hey tried with the specified file, I get this error now.

```
Error

The below parts won't be assembled due to data missing.
U5,SW1,C1,C2,C3,C4,C5,C6,C7,C8,R1,R2,R3,R4,R5,R6,L1,R7,R8,J1,R9,J2,J3,D1,D2,R11,U1,U2,U3,U4 designators don't exist in the BOM file.
18K,10UH,BUTTON,3.9N,47K,UART,A4988,100N,LED,10K,100K,10N,MP2307DN-LF-Z,2.4GHZ,6.8K,100U,22U,10U,VCC,MOTOR,1K,SS34LB,TA-03,NAME FOOTPRINT QUANTITY designators don't exist in the CPL file.
```

**Comment by mdenisov** [comment]
Hi 👋 Try with updated [BOM](https://github.com/mdenisov/feeder/blob/main/PCB/Feeder_v1_0_BOM.csv) file. I think the error is due to a mismatch in the BOM file and Gerber file.

**Comment by maksm** [comment]
Looking good now, will order 5pcs soon and report when I will assemble the unit. Might take a while :)

Thanks for all the assistance!

**Comment by mdenisov** [comment]
Great! I wish you good luck and look forward to your feedback!

You are welcome!
